### ISSUE TITLE
Error Creating AWS AppRunner Service: Failed to Stabilize

### ISSUE THREAD

**Issue by tomotsuguseki** [aws-samples/redcap-on-aws#11]
[devREDCapserviceapprunnerse-RuPWrGSN2hw2-system-logs.json](https://github.com/aws-samples/redcap-on-aws/files/14355523/devREDCapserviceapprunnerse-RuPWrGSN2hw2-system-logs.json)
[deployment_d640618634e34bfdb57b54846270f4ed.json](https://github.com/aws-samples/redcap-on-aws/files/14355499/deployment_d640618634e34bfdb57b54846270f4ed.json)

Hello,

I've encountered a new issue while trying to create an AWS AppRunner service as part of my dev stage deployment for REDCap with ``yarn deploy --stage dev``. The service creation fails with the following error message:

> Backend dev-REDCap-service/apprunner-service AWS::AppRunner::Service CREATE_FAILED Resource handler returned message: "Your service failed to create. Review the application logs to find the source of error and retry." (RequestToken: 3e95d37f-2f2e-7b50-48f3-d5109ba4bcfa, HandlerErrorCode: NotStabilized)

I understand that I need to review the application logs to pinpoint the exact cause of the failure, but I'm uncertain where to find these logs or how to access them.

Here's an excerpt from my stages.ts file where the configuration for the dev stage is defined:

```
import { RedCapConfig, DomainAppsConfig } from './prototyping';
import { Cpu, Memory } from '@aws-cdk/aws-apprunner-alpha';

const baseOptions = {
  name: 'REDCap',
  profile: 'default',
  region: 'us-east-1',
  allowedIps: ['my-ip-addresses'],
};

const dev: RedCapConfig = {
  ...baseOptions,
  hostInRoute53: false,
  phpTimezone: 'Asia/Tokyo',
  redCapS3Path: 'my-S3-folder/redcap14.1.6.zip',
  cronSecret: 'mysecret',
  email: 'my-email-address',
  port: 8080,
};

// Default route53NS config, no records are created.
const route53NS: DomainAppsConfig = {
  ...baseOptions,
  profile: '',
  region: 'us-east-1',
  apps: [],
  domain: 'my-redcap-domain',
};

export { prod, stag, dev, route53NS };

```

I would greatly appreciate any guidance on:
1. How to access the specific application logs that the error message refers to.
2. Any insights or common pitfalls that might lead to the NotStabilized error during AWS AppRunner service creation.

Thank you in advance for your help and support.

Best,

**Comment by jl4nz** [comment]
Hi, from the logs provided it seems that the image was not build correctly.

```
  "[AppRunner] Failed to pull your application image. Reason: ECR image doesn't exist. Confirm that your service is configured with an existing ECR image and retry.",
```

There should be a process on CodeBuild process you can check to see why it failed to push the image to ECR. 

Most likely, you need to fix this with an existing bucket, this path should exist in your S3 account. 

```
  redCapS3Path: 'my-S3-folder/redcap14.1.6.zip',
```

**Comment by tomotsuguseki** [comment]
Dear Jorge,

Thank you very much for your insightful response. I truly appreciate your effort to help me diagnose the issue.

I would like to clarify that, for security reasons, I modified some information, such as 'my-ip-addresses', 'my-S3-folder', 'my-email-address', and 'my-redcap-domain', replacing them with placeholders. Therefore, the specific issue might not be related directly to these elements.

Given your suggestion, I'm now looking into the CodeBuild process to understand why it might have failed to push the image to ECR. I suspect the root cause lies there, as you've pointed out.

I also checked the configurations related to the redCapS3Path, ensuring it accurately reflects the intended path in my S3 bucket. Your advice has guided me to reconsider aspects I might have overlooked.

Thank you once again for your valuable assistance. I'll keep you updated on my progress, and I'm hopeful that with your guidance.

Best,

**Comment by jl4nz** [comment]
Got it! You are very welcome, let us know if you need any help.

**Comment by tomotsuguseki** [comment]
Hi,

I suspect there might be an issue with my "dev-redcap-repository" in Amazon Elastic Container Registry (ECR) appearing to be empty, which could be contributing to the problem I'm facing.

Below, I've included an excerpt from my CodeBuild log for reference. Any insights or assistance in resolving this matter would be greatly appreciated. Thank you in advance for your time and support.

Best,

```
#9 importing cache manifest from 549244190344.dkr.ecr.us-east-1.amazonaws.com/dev-redcap-repository:14.1.6
#9 ERROR: 549244190344.dkr.ecr.us-east-1.amazonaws.com/dev-redcap-repository:14.1.6: not found

#22 [stage-0 14/16] RUN chown www-data -R /etc/redcap-entry && chmod a+x /etc/redcap-entry/*.sh && /etc/redcap-entry/setup_app.sh
#22 0.335 /bin/sh: 1: /etc/redcap-entry/setup_app.sh: not found
#22 ERROR: process "/bin/sh -c chown www-data -R /etc/redcap-entry && chmod a+x /etc/redcap-entry/*.sh && /etc/redcap-entry/setup_app.sh" did not complete successfully: exit code: 127
------
 > importing cache manifest from 549244190344.dkr.ecr.us-east-1.amazonaws.com/dev-redcap-repository:14.1.6:
------
------
 > [stage-0 14/16] RUN chown www-data -R /etc/redcap-entry && chmod a+x /etc/redcap-entry/*.sh && /etc/redcap-entry/setup_app.sh:
0.335 /bin/sh: 1: /etc/redcap-entry/setup_app.sh: not found
------
Dockerfile:48
--------------------
  46 |     # Container start scripts
  47 |     COPY scripts/ /etc/redcap-entry/
  48 | >>> RUN chown www-data -R /etc/redcap-entry && chmod a+x /etc/redcap-entry/*.sh && /etc/redcap-entry/setup_app.sh
  49 |     RUN touch /etc/msmtprc && chown www-data /etc/msmtprc
  50 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c chown www-data -R /etc/redcap-entry && chmod a+x /etc/redcap-entry/*.sh && /etc/redcap-entry/setup_app.sh" did not complete successfully: exit code: 127

[Container] 2024/02/26 08:45:56.543197 Command did not exit successfully docker build --cache-from $ECR_REPOSITORY_URI:$IMAGE_TAG --build-arg PHP_TIMEZONE=$PHP_TIMEZONE --build-arg LANG_S3_URI=$LANG_S3_URI --build-arg REDCAP_S3_URI=$REDCAP_S3_URI --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg PORT=$PORT --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t $ECR_REPOSITORY_URI:$IMAGE_TAG -t $ECR_REPOSITORY_URI:latest . exit status 1
[Container] 2024/02/26 08:45:56.552436 Phase complete: BUILD State: FAILED
[Container] 2024/02/26 08:45:56.552454 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker build --cache-from $ECR_REPOSITORY_URI:$IMAGE_TAG --build-arg PHP_TIMEZONE=$PHP_TIMEZONE --build-arg LANG_S3_URI=$LANG_S3_URI --build-arg REDCAP_S3_URI=$REDCAP_S3_URI --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg PORT=$PORT --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t $ECR_REPOSITORY_URI:$IMAGE_TAG -t $ECR_REPOSITORY_URI:latest .. Reason: exit status 1
[Container] 2024/02/26 08:45:56.584245 Entering phase POST_BUILD
[Container] 2024/02/26 08:45:56.584792 Running command docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
The push refers to repository [549244190344.dkr.ecr.us-east-1.amazonaws.com/dev-redcap-repository]
An image does not exist locally with the tag: 549244190344.dkr.ecr.us-east-1.amazonaws.com/dev-redcap-repository

[Container] 2024/02/26 08:45:56.607288 Command did not exit successfully docker push $ECR_REPOSITORY_URI:$IMAGE_TAG exit status 1
[Container] 2024/02/26 08:45:56.612843 Phase complete: POST_BUILD State: FAILED
[Container] 2024/02/26 08:45:56.612930 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker push $ECR_REPOSITORY_URI:$IMAGE_TAG. Reason: exit status 1
```

**Comment by jl4nz** [comment]
Thank you for the logs. 

>#9 importing cache manifest from 549244190344.dkr.ecr.us-east-1.amazonaws.com/dev-redcap-repository:14.1.6
> #9 ERROR: 549244190344.dkr.ecr.us-east-1.amazonaws.com/dev-redcap-repository:14.1.6: not found

This part is OK, as it will throw an error as you haven't build a previous version of the image yet, cache.

>#22 0.335 /bin/sh: 1: /etc/redcap-entry/setup_app.sh: not found
>#22 ERROR: process "/bin/sh -c chown www-data -R /etc/redcap-entry && chmod a+x /etc/redcap-entry/*.sh && /etc/redcap-entry/setup_app.sh" did not complete successfully: exit code: 127

This must be the real reason. It's directly related to the docker build command executed in CodeBuild and it seems the resources from the deployment where not uploaded. 

Can you check that in your files you have files in the folder `containers/redcap-docker-apache` ? in there you should see the folders and scripts just like in the repo. Included the `./scripts/setup_app.sh`.

Next, in the AWS Console, you can check what asset was use in code build. You can go to CodeBuild -> Build Projects and in the build history, download the `Source version` of the execution. This is a zip file and the contents should look similar to this:

<img width="299" alt="Screenshot 2024-02-27 at 17 03 52" src="https://github.com/aws-samples/redcap-on-aws/assets/94814971/ebf1a869-6f8d-4e61-bfaa-c8c36d883617">

(some variation can exist, but in there the `setup_app.sh` related to the error should exist.)

**Comment by tomotsuguseki** [comment]
[9ba1d5952daeb7a23d8a49f5423c1d7a604d41c35d2d414c173a4feda2369168.zip](https://github.com/aws-samples/redcap-on-aws/files/14417887/9ba1d5952daeb7a23d8a49f5423c1d7a604d41c35d2d414c173a4feda2369168.zip)

Thank you for your help.
I could find and downloaded the attached zip file from CodeBuild.
What's the next step?

**Comment by jl4nz** [comment]
The files looks to be OK, so I would recommend a few things:

I suspect the problem might be something similar to the problem described here related to git and windows: https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory/29045187#29045187

1. Delete the repo from your computer
2. Run `git config --global core.autocrlf false`
3. Run `git clone https://github.com/aws-samples/redcap-on-aws`
4. Configure and try deploying again

From your files , opening the Dockerfile shows the a non batch format. `CRLF`

<img width="471" alt="Screenshot 2024-02-27 at 21 01 19" src="https://github.com/aws-samples/redcap-on-aws/assets/94814971/3c0e159c-4693-4a74-b967-029836f07921">

This must be `LF` to work. 

<img width="857" alt="Screenshot 2024-02-27 at 21 03 16" src="https://github.com/aws-samples/redcap-on-aws/assets/94814971/cc29afcb-83a7-4c56-98cd-13d6af196059">

**Comment by jl4nz** [comment]
Forgot to mention. You can keep a copy of your `stages.ts` and `./sql/redcapConfig.sql` files to restore your settings after cloning again.

**Comment by jl4nz** [comment]
Last, VSCode has a function to change the end line sequence if you have doubts for the `stages.ts` and `./sql/redcapConfig.sql` files

<img width="667" alt="Screenshot 2024-02-27 at 21 25 05" src="https://github.com/aws-samples/redcap-on-aws/assets/94814971/83b26810-03be-4d57-8176-815be99f191b">

**Comment by jl4nz** [comment]
We just release this as an alternative to avoid the above (windows+git), you can download the new versions from here https://github.com/aws-samples/redcap-on-aws/releases

**Comment by tomotsuguseki** [comment]
The deployment has been successfully completed! 
A key change in our approach involved downloading the latest code and updating the Git configuration as suggested.
Thank you to troubleshooting and implementing the solution. Your hard work and dedication are greatly appreciated.
