### ISSUE TITLE
Error due to Existing Log Group Resource

### ISSUE THREAD

**Issue by tomotsuguseki** [aws-samples/redcap-on-aws#18]
Hi, thank you for new release. I have another question.

I recently attempted to deploy the latest release, but unfortunately, I encountered a new error that persisted across multiple attempts. Despite starting the deployment process from scratch on several occasions, I consistently faced the same issue. However, surprisingly, I could access my REDCap without fixing the error.

```
✖  Errors
   EC2Server ROLLBACK_COMPLETE
   deleteStackSfnLogGroup: Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/vendedlogs/states/deleteStackSfnLogGroup"}' already exists." (RequestToken: 0ab09a58-75d6-a275-89f6-3c888622940c, HandlerErrorCode: AlreadyExists)
```

After deleting '/aws/vendedlogs/states/deleteStackSfnLogGroup', the error message disappeared, but I'm not sure it's OK.

My question is, what is the cause of the error?

Thank you in advance for your time and effort.

P.S. In the section '5.1.1 Use redcap as a subdomain' within the README.md file, should the value for `hostInRoute53` be set to 'acme.com' rather than `true`?

**Comment by jl4nz** [comment]
The `EC2Server` stack is an optional feature that you can safely delete and re-create again. It's there to execute REDCap on a temporary EC2 instance and do long running requests (import projects for example). I think what is happening is that the new code version was trying to deploy a new resource for this. Your solution of deleting the log was correct, but I would also recommend two things:

1. Only enable the EC2Stack in your `stage.ts` file when you need it, so generally this should be disabled. 
    ```ts
       // ec2ServerStack: { .... } 
    ```
2. You can try to delete  **only** the `EC2stack` from CloudFormation (if exists) to make sure future deployments will not fail. Although, when its deployed, it should be automatically be deleted after the configured time. 

I will keep an eye for this next week, we might be able to improve this log issue.

**Regarding the domain:**

I think you case is to setup redcap at this domain `redcap.tomotsuguseki.com` using an existing registered domain. In the README `5.1.1` is the correct section. However, the `acme.com` is a fake domain for demo purposes.

```
For explanation purposes, we will assume we own the acme.com domain and our intention is to deploy REDCap at the redcap.acme.com.
```

So your setting should be:

```ts
const prod: RedCapConfig = {
  ...baseOptions,
  hostInRoute53: true,
  domain: 'tomotsuguseki.com',
  subdomain: 'redcap',
```

**Comment by tomotsuguseki** [comment]
Thank you for your reply during weekend.
I commented out the `ec2ServerStack`, destroyed, and re-deployed the REDCap for simplicity, instead of updating existing environment. The deployment succeeded, but I have a new problem.

**Regarding the domain**

During my first attempt, `hostInRoute53: 'tomotsuguseki.com'` worked better than `hostInRoute53: true`.
This time, `hostInRoute53: true` can deploy the REDCap without error, but I couldn't access the REDCap through 'redcap.tomotsuguseki.com' although the status is `active`.

Thank you for advance for your help at your convenience.

**Comment by jl4nz** [comment]
You're welcome.

I suspect there might be something from the previous deploy interfering with the domain configuration. I'll help you fix it, please check the following:

1. In your AWS Console / Route 53 there should be now 2 HostedZones now. One for `tomotsuguseki.com` and a new one for `redcap.tomotsuguseki.com`

2. In `redcap.tomotsuguseki.com` Zone, you should have only 2 records NS and SOA types.

3. In the `tomotsuguseki.com` Zone please check:
    3.1 There should be one `A` record with value to the `xxxxxx.awsapprunner.com.`
    3.2 There's one record name with `redcap.tomotsuguseki.com` of Type `NS`. The `value` of this record should be the same as the `NS` record in the previous hosted zone (`redcap.tomotsuguseki.com`).
 
Let's confirm this first. Thanks.

**Comment by jl4nz** [comment]
I'm sorry, I've updated my previous comment, I made a mistake.

**Comment by jl4nz** [comment]
This is what we are deploying for reference:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-routing-traffic-for-subdomains.html
Section `Create a hosted zone for the subdomain, and create records in the new hosted zone`

**Comment by tomotsuguseki** [comment]
Thank you for your instruction. I checked accordingly:

1. There are two Hosted Zones as you said.
2. Four values in the record (name: tomotsuguseki.com, type: NS) at tomotsuguseki.com, and another one (name: redcap.tomotsuguseki.com, type: NS) at redcap.tomotsuguseki.com were different each other. 

Is it OK?

**Comment by jl4nz** [comment]
I see... thank you for checking. 

>1. There are two Hosted Zones as you said.

This is good. 

>2. Four values in the record (name: tomotsuguseki.com, type: NS) at tomotsuguseki.com, and another one (name: redcap.tomotsuguseki.com, type: NS) at redcap.tomotsuguseki.com were different each other.

Yes, they should be different. 

HostedZone: **tomotsuguseki.com**
```
tomotsuguseki.com	nameserver = ns-1519.awsdns-61.org.
tomotsuguseki.com	nameserver = ns-1645.awsdns-13.co.uk.
tomotsuguseki.com	nameserver = ns-24.awsdns-03.com.
tomotsuguseki.com	nameserver = ns-657.awsdns-18.net.

redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.org.
redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.co.uk.
redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.com.
redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.net.
```

In the second hosted zone `redcap.tomotsuguseki.com` created by the deployer:

HostedZone: **redcap.tomotsuguseki.com**

These nameserver should match the one in your tomotsuguseki.com HostedZone.

```
redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.org.
redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.co.uk.
redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.com.
redcap.tomotsuguseki.com	nameserver = ns-xxxx.awsdns-xxxx.net.
```

**Comment by tomotsuguseki** [comment]
Thank you for your confirmation.
Should I wait for next update?

**Comment by jl4nz** [comment]
No, this should work on this version. 

Can you please confirm that the NS servers from the **HostedZone: redcap.tomotsuguseki.com** are the same for in the **HostedZone: tomotsuguseki.com** for `redcap.tomotsuguseki.com`  record?

**Comment by tomotsuguseki** [comment]
No, there isn't the record named `redcap.tomotsuguseki.com` in the  **HostedZone:** tomotsuguseki.com.

**Comment by jl4nz** [comment]
OK, this is the problem then. Give me a few minutes to investigate.

**Comment by jl4nz** [comment]
I think I found the issue. Investigating the code and the README there's a difference for this case.

Can you try deploying with this: 

```
const prod: RedCapConfig = {
  ...baseOptions,
  hostInRoute53: 'tomotsuguseki.com',
  domain: 'tomotsuguseki.com',
  subdomain: 'redcap',
  ```
  
 If there's any error that the zone exist, you can delete the **HostedZone** `redcap.tomotsuguseki.com`  and try again.

**Comment by tomotsuguseki** [comment]
Thank you for your help.
After the change, I could access my REDCap on `redcap.tomotsuguseki.com` without problem.
