### ISSUE TITLE
デプロイ環境作成時のエラーに関する質問

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#30]
お世話になります。
README.ja.mdの記述に従い、「REDCapアプリケーションのデプロイ」-「2. 依存関係のインストール」を実行したところ、エラーが発生しました。
このエラーは無視しても後続処理は継続できましたが、本当に無視しても問題ないのか分からないため教えてください。
エラー内容は添付を参照してください。
（pythonやvisualstudioのインストールが求められているようです）

![スクリーンショット 2024-04-16 154946](https://github.com/aws-samples/redcap-on-aws/assets/167844581/d7c1cd15-566b-4adc-b0e2-573eb998b195)
![スクリーンショット 2024-04-16 155046](https://github.com/aws-samples/redcap-on-aws/assets/167844581/71c7145c-3737-47e3-b4be-5a15a4e588cd)

**Comment by jl4nz** [comment]
こんにちは！ 報告ありがとうございました。

追加のノード依存関係を構築するには、Python をインストールする必要があるようです。
Pythonに関連するnode-gypの次の手順を試していただけますか?

https://github.com/nodejs/node-gyp?tab=readme-ov-file#on-windows

**Comment by ouh-kaneko** [comment]
こんにちは、情報ありがとうございます。
Pythonのインストールは問題なく実行できました。
ですが、今度は別のエラーが発生しています。
ModuleNotFoundError: No module named 'distutils'に心当たりはありますか？
![スクリーンショット 2024-04-24 165137](https://github.com/aws-samples/redcap-on-aws/assets/167844581/1e99fd77-3cb0-4e8a-9929-cad33b160b56)
[build.log](https://github.com/aws-samples/redcap-on-aws/files/15090665/build.log)

**Comment by ouh-kaneko** [comment]
こんにちは、回答ありがとうございます。

pip install setuptools をインストールしたところ、エラーは解消されました。
ありがとうございます。
エラーは全て解消されましたのでCloseとさせて頂きます。
