### ISSUE TITLE
リードレプリカの設定が正しく行われていない可能性がある

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#32]
お世話になります。

stage=devでデプロイを行い、開発環境を作成してみました。
REDCapは実行可能な状態となりましたが、管理画面を表示した際、
「読み込みレプリカデータベースがオフラインになっている可能性があります」と警告メッセージが表示されます。

AWSコンソールのRDSを確認すると、AuroraV2のリージョン別クラスターが作成されており、
リーダーインスタンス、ライターインスタンス共にステータスは利用可能となっています。

database.phpにリードレプリカの設定を追記していると考えられますが、
AppRunnerで稼働中のコンテナイメージのファイル内容を確認する方法はありますか？

![スクリーンショット 2024-05-09 154049_new](https://github.com/aws-samples/redcap-on-aws/assets/167844581/3396019b-e42d-4f17-87e8-4dfa388b2955)
【REDCapの管理画面で表示されるメッセージ】

**Comment by jl4nz** [comment]
新しいリリース v.1.0.4 をチェックしてください。 そこでレプリカの問題を修正しました。

**Comment by ouh-kaneko** [comment]
お世話になっております。

v1.0.4で警告メッセージは表示されなくなりました。
ただ、環境を初めて作成する際、Apprunnerのサービス設定時にエラーが発生します。

redcap_configure.shの44行目のif文内では、redcap_configテーブルを更新していますが、
初めて環境を作成する場合、80行目のinstall.phpでredcap_configテーブルは作成されるはずです。
そのため、44行目のif文は81行目以降にすべきと考えます。
確認をお願い致します。

**Comment by jl4nz** [comment]
FY: https://github.com/aws-samples/redcap-on-aws/pull/38/files

**Comment by ouh-kaneko** [comment]
修正ありがとうございます。
事象は解決されたとしてCloseにしたいと思います。
