### ISSUE TITLE
Auroraのバックアップ／リストアについて確認したい

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#33]
お世話になっております。

Auroraデータベースは、毎日バックアップを取得していますが、
スナップショットの復元を実行すると新規のDBインスタンス識別子として復元が行われます。

redcap-on-awsでは、AppRunnerからAuroraへの接続についてはデプロイ時に自動で設定されますが、
スナップショットから復元を行った場合、AppRunnerからのDB接続先変更はどのように行えば良いのでしょうか？

**Comment by jl4nz** [comment]
お世話になっております。

最初の推奨事項は、24 時間有効になっている Backtrack を使用してみることです。 最大72時間まで変更可能です。 

https://github.com/aws-samples/redcap-on-aws/blob/main/prototyping/constructs/AuroraServerlessV2.ts#L116
https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Managing.Backtrack.html

復元:
ここのコードを変更する必要があります: https://github.com/aws-samples/redcap-on-aws/blob/main/prototyping/constructs/AuroraServerlessV2.ts#L84 を次のように変更します。 https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseClusterFromSnapshot.html

これがお役に立てば幸いです

**Comment by ouh-kaneko** [comment]
お世話になっております。

推奨事項、ならびに復元方法の変更箇所について、説明ありがとうございます。
スナップショットからの復元について、近日中に確認致します。
確認ができましたら、Closeにしたいと思います。

**Comment by ouh-kaneko** [comment]
リストアでスナップショットを利用する場合が正しく処理できません。

スナップショットを用いながら新規に環境を構築する場合、
redcap_configure.shの31行目でDBに接続しようとした際に
[Access denied for user 'dbadmin'@'10.0.3.97' (using password: YES)]のエラーが発生しました。

また、既存環境に対してスナップショットを用いてリストアを行う場合、
[Database:ExportsOutputFnGetAttRDSV2ServerlessAuroraDatabaseD452A1FAReadEndpointAddress930594E2 cannot be updated as it is in use by dev-REDCapDev-Backend]のエラーが発生しました。

AuroraServerlessV2.ts内では、aws_rds.DatabaseClusterを実行していた部分をコメント化し、
aws_rds.DatabaseClusterFromSnapshotを実行するように修正しました。
また、その際に設定するプロパティ値は、snapshotIdentifierを追加したのみで、
他はaws_rds.DatabaseCluster実行時のプロパティ値をそのまま使用しています。


新規環境の作成（環境の複製）、また、既存環境に対するスナップショットを用いた巻き戻しについて、
具体的にどのように設定すればよろしいのでしょうか？

**Comment by jl4nz** [comment]
新しいクラスターが同じコンストラクター ID を使用していることが原因のようです。 今日はデータベース機能を備えた新しいリリースに取り組む予定です。
 
 1. パススナップショットID.
 2. データベースリーダーのパス番号 (無効化可能)

e.g

```
this.aurora = new aws_rds.DatabaseClusterFromSnapshot(
        this,
        'newId',
        databaseProps,
      );
```

テストのために新しいブランチをここに投稿します。
Thank you!

**Comment by jl4nz** [comment]
これは https://github.com/aws-samples/redcap-on-aws/tree/33-database-features 、3 つの新しいユースケースのサポートが強化された新しいブランチです。 これはまだテスト中です。

1.「リーダー」の数を設定する (stages.ts ---> dbReaders: 0 無効を意味します)
2. 新しい環境をデプロイする: [docs](https://github.com/aws-samples/redcap-on-aws/blob/33-database-features/README.ja.md#%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9-%E3%82%B9%E3%83%8A%E3%83%83%E3%83%97%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%E3%81%8B%E3%82%89%E3%81%AE%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E3%81%BE%E3%81%9F%E3%81%AF%E5%BE%A9%E5%85%83)

現時点で、スナップショットを使用して既存のデータベースを更新するには、「バックエンド」スタックを削除するという前の手順が必要です (ドキュメント セクションに詳細があります)。 これは上記のエラーを防ぐためです (... cannot be updated as it is in use by dev-REDCapDev-Backend....) 。

**Comment by ouh-kaneko** [comment]
新しいブランチについて確認致しました。
対応ありがとうございます。

1. リーダーの数の設定については、0を設定して想定通りリーダーインスタンスが作成されないことを確認しました。
2. スナップショットを使用してデータベースの新規構築では、後続のApprunnerでもエラーが発生せず、環境が構築できました。
3. スナップショットを使用して既存環境のデータベース復元ですが、「バックエンド」スタックを削除することは別の問題が発生します。
　REDCap内で使用するファイルのアップロード先としてS3を使用する場合、「バックエンド」スタックでバケットを作成します。
　「バックエンド」スタックを削除すると、REDCap内で使用しているS3バケットがアップロードしたファイル含めて削除されます。（または、再作成時に別のS3バケットが使用されるようになります）

また、既存環境更新時にredcapConfig.sqlが再実行される問題があります。
redcap_configure.sh内の84行目以降では、既にredcapConfig.sqlが実行されている場合は再デプロイ時はスキップされるはずですが、
redcap_configテーブルのamazon_s3_secretを取得する際、該当値はREDCapで暗号化して格納されているいるため、
redcap_configure.sh内の86行目のif文は必ず不成立となり、redcapConfig.sqlが再実行されます。
これにより、仮にS3バケットを別で用意し、REDCapで設定変更していた場合もデプロイ時に元に戻ってしまいます。

**Comment by jl4nz** [comment]
コメントありがとうございます。

実際、バックエンドを削除すると、これらすべての問題と彼の S3 データが意味されます。

スタックの削除を避けるために、スナップショットを使用するときに新しいデータベース リソースを作成するようにブランチを更新しました。

これはまだテスト中です。

**Comment by jl4nz** [comment]
```ts
this.aurora = new aws_rds.DatabaseClusterFromSnapshot(
        this,
        'ServerlessAuroraDatabaseFromSnapshot',
        databaseProps,
      );

```

VS
```ts
this.aurora = new aws_rds.DatabaseCluster(this, 'ServerlessAuroraDatabase', databaseProps);
```

**Comment by jl4nz** [comment]
https://github.com/aws-samples/redcap-on-aws/pull/40 は審査を受ける予定です。

本日のアップデートにより、スナップショットの作成またはスナップショットからの復元が可能になります。 バックエンド スタックを削除する必要はありません。さらに問題がある場合はお知らせください。

フィードバックをお寄せいただきありがとうございます。

**Comment by jl4nz** [comment]
もう一つ更新です。

生成される CDK ID は次の形式になります。
        `ServerlessAuroraDatabaseFromSnapshot-${createHash('sha1').update(props.snapshotIdentifier).digest('hex')}`,


これは、連続したスナップショットを確実に展開できるようにするためです。

**Comment by ouh-kaneko** [comment]
修正された内容を確認しました。
既存環境もスナップショットから復元できました。
対応頂きありがとうございます。
このissueはCloseに致します。
