### ISSUE TITLE
docs/ja/devenv.md　Aurora Serverless v1→v2への変更は予定されていますか

### ISSUE THREAD

**Issue by ouh-hs** [aws-samples/redcap-on-aws#34]
開発環境（stage = dev）としてデプロイしたところ、Aurora V2で環境が作成されました。

（GitHub）/redcap-on-aws/docs/ja/devenv.md
上記では「開発環境ではAurora Serverless v1、本番環境ではv2を使用します。」と記載されておりますが、
今後ドキュメントの修正は予定されていますか？

**Comment by ouh-hs** [comment]
dbreplica.mdの修正ありがとうございます。
devenv.mdの下記の記載について、「開発環境もAurora Serverless v2を使用する」が正しいですか？

https://github.com/aws-samples/redcap-on-aws/blob/main/docs/ja/devenv.md#database
> Database
> 1.開発環境ではAurora Serverless v1、本番環境ではv2を使用します

**Comment by jl4nz** [comment]
これは、ドキュメントが更新されなかった前のバージョンの名残でもあります。
このプロジェクトでは、複雑さを避けるために V2 のみを使用します。
できるだけ早く更新します。 どうもありがとうございます。

PD: 参考までに、最初は SST データベースを使用しました。 https://docs.sst.dev/constructs/RDS ですが、これは Aurora サーバーレス V1 のみです。

**Comment by ouh-hs** [comment]
@jl4nz 
ドキュメントの修正ありがとうございました!!（確認が遅くなり申し訳ないです）
