### ISSUE TITLE
開発環境のAurora リードレプリカを作成しないようにしたい

### ISSUE THREAD

**Issue by ouh-hs** [aws-samples/redcap-on-aws#35]
開発環境もAurora v2となり分かりやすくなりましたが、
費用面から、開発環境ではリードレプリカの設定は「なし」としたいと考えております。
リードレプリカを「なし」とした際、どのような影響が考えられるでしょうか。
また、CDKコードの変更を行いたいのですが、どのファイルを修正すればよいでしょうか。

**Comment by jl4nz** [comment]
その影響は、クラスターに単一のライター/リーダーが存在することです。

このプロパティ「readers」を削除またはコメント化することができます。
https://github.com/aws-samples/redcap-on-aws/blob/v1.0.4/prototyping/constructs/AuroraServerlessV2.ts#L100

**Comment by ouh-hs** [comment]
影響について理解いたしました。
コメント化してTryしてみます。
Thanks for your help！

**Comment by ouh-hs** [comment]
closeします。
