### ISSUE TITLE
UpdateDeploymentCommand実行でエラーが発生する

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#44]
いつも大変お世話になっております。

デプロイを実行し、UpdateDeploymentCommandを実行するとRead timeout on endpoint URLエラーが発生しました。
何か設定等を変更する必要があるのか、確認させて下さい。

![image](https://github.com/aws-samples/redcap-on-aws/assets/167844581/4152bcb3-8a0a-4a6a-984c-1ec6069dded0)

![image](https://github.com/aws-samples/redcap-on-aws/assets/167844581/d1460a48-3226-4958-bb99-fc8a03b998dc)

**Comment by jl4nz** [comment]
このデプロイメントが dev: `yarn dev --stage myStage ` を使用している場合、`aws lambda invoke` は別のターミナルで実行する必要があります。

それ以外の場合、これが`yarn deploy --stage myStage` の場合、ラムダはタイムアウトする可能性がありますが、新しいビルドがトリガーされます。https://console.aws.amazon.com/codesuite/codebuild/projects でビルド状態を確認してください。

**Comment by ouh-kaneko** [comment]
私は、環境を`yarn deploy --stage dev`で作成しています。
ラムダはタイムアウトしていますが、CodeBuildでは正常に実行できていたことが確認出来ました。
回答ありがとうございました。
