### ISSUE TITLE
MTAの確認

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#47]
いつも大変お世話になっております。

この環境で作成されるAppRunner用コンテナイメージでは、
メールを送信するためのミドルウェアは何を使用しているのか教えてください。

**Comment by jl4nz** [comment]
遅れて申し訳ありません。

バージョン v0.9.0 では、`postfix` が `msmtp` に置き換えられました。

https://wiki.debian.org/msmtp

REDCap の電子メール操作 (smtp クライアント) には、postfix と互換性のない API が必要です。

**Comment by ouh-kaneko** [comment]
回答ありがとうございます。
確認できましたので、Closeと致します。
