### ISSUE TITLE
Error "Command 'deploy' not found" when running `yarn deploy --stage <my_stage_name>`

### ISSUE THREAD

**Issue by tomotsuguseki** [aws-samples/redcap-on-aws#48]
When I tried to update REDCap with `yarn deploy --stage <my_stage_name>`, I encountered the following error: `error Command "deploy" not found.`

I have verified that `package.json` contains the deploy script, but I am not sure how to resolve this issue. Could you please provide guidance on what steps I should take to fix this?

**Comment by jl4nz** [comment]
Hi! let me try to help. 

I haven't encounter this issue, so lets check some steps. 

```
yarn install // this command is succeeded?
yarn --version  // what is the version you have installed?
```

Also, make sure you are executing `yarn deploy --stage ` in the `root` folder `your_folder/redcap-on-aws/$`

**Comment by tomotsuguseki** [comment]
Dear Jorge,
Thank you for your prompt reply. I realized that I simply forgot to set the current directory before running yarn deploy. :(
