### ISSUE TITLE
Questions Regarding REDCap Upgrade and Language File Addition

### ISSUE THREAD

**Issue by tomotsuguseki** [aws-samples/redcap-on-aws#51]
I have two small questions:
1. When upgrading REDCap, which file should I use: the "Fresh Install Package" (e.g., redcap1.2.3.zip) or the "Upgrade Package" (e.g., redcap1.2.3_upgrade.zip)? Both are available from the REDCap community.
2. Where should I add a new language file when adding a language file?

**Comment by jl4nz** [comment]
1. Always use Fresh/Full install packages redcap1.2.3.zip. Each deploy builds a new docker image stored in Amazon ECR.
2. For new languages (ini files) put them in `./packages/REDCap/languages` folder. Then you will need to deploy with the option to rebuild new image (to include these new files) , https://github.com/aws-samples/redcap-on-aws?tab=readme-ov-file#3-call-the-container-build-and-deploy-function

**Comment by jl4nz** [comment]
Let me clarify 2 a bit more. 

1. Add the packages ini files
2. Deploy the app `yarn deploy ... `
3. Execute the lambda command in the output of `UpdateDeploymentCommand` from the terminal

**Comment by tomotsuguseki** [comment]
Thank you for your advice. Both steps went well.
