### ISSUE TITLE
Unable to update redcap 14.4.x -> 14.5.x

### ISSUE THREAD

**Issue by tomotsuguseki** [aws-samples/redcap-on-aws#55]
When I recently tried updating redcap from 14.4.1 to 14.5.0 / 14.5.1, deployment was successfully completed but white page was appeared and unable access to my redcap. Could you provide guidance on how to resolve this issue? Any troubleshooting steps or known issues with this version update would be greatly appreciated.

**Comment by jl4nz** [comment]
Most likely you are missing the last step to run upgrade.php.

**4. Run REDCap upgrade function**

Before executing this command, it is recommended to do a database snapshot or get familiar with [Aurora backtrack window feature](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Managing.Backtrack.html) in case of failure.
Once deployment is complete, REDCap's database is updated/migrated by accessing https://<your_domain>/upgrade.php?auto=1.

Alternatively, you can access in your browser to https://<your_domain>/upgrade.php and click on Option A --> Upgrade to upgrade the database tables.

**Comment by tomotsuguseki** [comment]
Oops!
I forgot accessing https://<your_domain>/upgrade.php?auto=1 **BEFORE** accessing redcap home page.
The update successfully done. Thank you!

p.s. I also report that I could run ver. 1.0.7. successfully.
