### ISSUE TITLE
処理性能改善の確認

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#56]
EC2、RDSを用いてREDCap環境を作成した場合と比べ、REDCap on AWSで環境を構築した場合、REDCap画面上でレコード登録処理を行うとおよそ3秒以上のレイテンシーが毎回発生します（通常：2秒以内、REDCap on AWS：3秒以上）。
AppRunnerのvCPU・メモリ、Auroraの最小ACU変更等の調整を行い性能改善を試みましたが、登録処理の時間は変化しませんでした。
また、Performance Isightsで確認した際も特に気になった点はなく、slow query（long_query_time = 1）として検出されるSQLもありませんでした。
ただし、Auroraのerror logにて、buffer poolのサイズ変更が頻繁に発生していました。

何か改善できる事項がありますでしょうか？

**Comment by jl4nz** [comment]
データベースのログエラーのコピーを取得することは可能ですか?

「innodb_buffer_pool_size」は Aurora serverless によって自動的に処理され、サーバーの負荷に応じてリアルタイムで変化することが予想されます。

https://dev.mysql.com/doc/refman/9.0/en/innodb-buffer-pool-resize.html

> Starting the server with [--log-error-verbosity=3](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_log_error_verbosity) logs additional information to the error log during an online buffer pool resizing operation. Additional information includes the status codes reported by [Innodb_buffer_pool_resize_status_code](https://dev.mysql.com/doc/refman/8.4/en/server-status-variables.html#statvar_Innodb_buffer_pool_resize_status_code) and the percentage progress value reported by [Innodb_buffer_pool_resize_status_progress](https://dev.mysql.com/doc/refman/8.4/en/server-status-variables.html#statvar_Innodb_buffer_pool_resize_status_progress).
```

役に立つかどうかは分かりませんが、挿入の問題ではなく、読み取りの問題かもしれません。MYSQL のチューニングが必要になるかもしれません。

たぶんこれが役に立つでしょう:

https://github.com/aws-samples/redcap-on-aws/blob/main/stacks/Database.ts#L42

```ts
parameterGroupParameters: {
      max_allowed_packet: '4194304',
      read_rnd_buffer_size: '262144',
      sort_buffer_size: '2097152',
    },
```

**Comment by ouh-kaneko** [comment]
[log-events-viewer-result.csv](https://github.com/user-attachments/files/16384571/log-events-viewer-result.csv)
Auroraのエラーログは添付ファイルを参照して下さい。

Auroraはstages.tsでdbReaders: 1を設定しています。
Auroraのチューニングとして提案頂いた内容を設定してみましたが、想定した効果は得られておりません。
※現在Auroraに設定しているパラメータ
`    parameterGroupParameters: {
      long_query_time: '1',
      max_allowed_packet: '134217728',
      sort_buffer_size: '2097152',
      read_rnd_buffer_size: '262144',
      time_zone: 'Asia/Tokyo',
    },`
　max_allowed_packetは、REDCapが推奨する値まで設定値を増やしました。

**Comment by jl4nz** [comment]
ログをありがとうございます。問題ないようです。

REDCap のデータベースに対する IAM 認証が原因ではないかと疑っています。`Backend.ts` ファイルでこれを変更することは可能です。`USE_IAM_DB_AUTH: 'false',`

来週、データベースの問題ではないと思うので、これを使っていくつかテストをします。

**Comment by jl4nz** [comment]
アプリケーション ログでは、POST の後に GET メッセージが続くのは、レコードを保存する時間に関連しています。

下の図は、約1秒かかった2つの記録保存アクションです。

<img width="1400" alt="Screenshot 2024-07-26 at 19 38 51" src="https://github.com/user-attachments/assets/d514a1b4-5d0b-45a2-834e-e7b802d0befe">

**Comment by ouh-kaneko** [comment]
IAM認証について、設定を変更してみました。
`USE_IAM_DB_AUTH: 'false',`

ただ、変更による改善効果は得られなかったと感じています。
Apache、PHPの設定等の問題でしょうか？

**Comment by ouh-kaneko** [comment]
比較した既存環境ではphp-fpmが動作していることを確認しました。
このプロジェクトで構築される環境とは違うと思いますが、影響はあると考えられますか？

**Comment by jl4nz** [comment]
こんにちは。返信が遅くなって申し訳ありません。

データベースの IAM 認証 (true/false) の変更も、私のテストではパフォーマンスへの影響は見られませんでした。したがって、問題はここにはないと考えられます。

PHP-FPM については、OPCACHE が有効になっている場合も違いが出る可能性があります。現在、このプロジェクトでは、動作が異なりますが管理が簡単な「mpm_prefork」をデフォルトとして使用しています。

このブランチ (https://github.com/aws-samples/redcap-on-aws/pull/60) で「opcache」を有効にしました。これは、直面している問題の解決に役立つ可能性があります。デプロイする前に `yarn install` を実行し、イメージの再構築コマンドを使用してください。

**Comment by ouh-kaneko** [comment]
修正ありがとうございます。
このブランチを私の環境に適用してみたところ、処理性能に改善が見られました（0.5秒程度改善）。

AppRunnerとECS on Fargateを比較したところ、AppRunnerのほうが若干処理が遅くなる傾向があるようです。
AppRunnerでこれ以上の劇的な改善は、現時点では難しいのではないかと思います。

**Comment by jl4nz** [comment]
はい、現時点では、FPM または類似のものを含めるには、いくつかの大きな変更なしでは難しいでしょう。ブランチをマージしました。新しいリリースをすぐに行います。

**Comment by ouh-kaneko** [comment]
ご対応頂きありがとうございます。
ブランチをマージ頂きましたのでクローズにします。
