### ISSUE TITLE
WafのAWSマネージドルールによるREDCap機能のBLOCK

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#57]
AWSManagedRulesSQLiRuleSetにより、REDCapの処理に影響がありましたので報告します。
推奨する改善方法がありますでしょうか？
※可能な限りCountへの変更は最小限とし、Block出来るように設定したいと考えております
①REDCapでフォームデザイン時、自動計算項目の計算式に「if([item]=’’, ‘‘, ‘‘)」の式を入力した場合、SQLi_Bodyルールに抵触する
②URLのQueryStringにて「id=1--1」等の値が設定された場合にSQLi_QueryArgumentsルールに抵触する

**Comment by jl4nz** [comment]
これを解決するには 3 つの方法があります。

1. ルールを除外できます。
```ts
{
    name: 'AWS-AWSManagedRulesSQLiRuleSet',
    rule: {
      name: 'AWS-AWSManagedRulesSQLiRuleSet',
      priority: 500,
      statement: {
        managedRuleGroupStatement: {
          vendorName: 'AWS',
          name: 'AWSManagedRulesSQLiRuleSet',
          excludedRules: [{ name: 'SQLi_QUERYARGUMENTS' }, { name: 'SQLi_Body' }],
        },
      },
      overrideAction: {
        none: {},
      },
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: 'AWS-AWSManagedRulesSQLiRuleSet',
      },
    },
  },
```

2. REDCapシステム内の影響を受けるURIに対してのみ、(1)と同じことを行います。

理想的には (2) を行うべきですが、システム内のどの URI または関数がこれによって影響を受けるかはわかりません。

**Comment by ouh-kaneko** [comment]
提案ありがとうございます。
2.の方法が可能か検討します。

**Comment by ouh-kaneko** [comment]
この問題については、組織ポリシーに従い、個別に検討を進めます。
1.の提案で様子を見つつ、2.の方法を考えていく予定です。
issue自体は提案頂いた内容で一旦クローズとさせて頂きます。
