### ISSUE TITLE
AuroraMySQLのバージョンとマイナーバージョン自動アップグレードについて

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#58]
現在、ソースコードではAuroraMySQLのバージョンはLTSである3.04が指定されていますが、
マイナーバージョン自動アップグレードが有効化されているため、非LTSである3.05.2にアップグレードされます。

このシステムでは、AuroraMySQLのバージョンはLTSを使用することが望ましいでしょうか？
それとも、マイナーバージョン自動アップグレードを有効化し、非LTSのバージョンに更新することが望ましいでしょうか？

※LTSバージョンを使用する場合、マイナーバージョン自動アップグレードは有効化しないことが推奨されています。
https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.Versions.html#AuroraMySQL.Updates.LTS

**Comment by jl4nz** [comment]
これは、組織独自の好みに少し関連しています。答えは、同じページの上部に一部記載されています。

```
ほとんど Aurora MySQL クラスターでは、LTS リリースを使用する代わりに、最新リリースへのアップグレードを推奨します。これにより、マネージドサービスとして Aurora を利用して最新の機能とバグ修正にアクセスできます。LTS リリースは、次の特性を持つクラスターを対象としています。

重要なパッチの稀な問題以外のアップグレードのために、Aurora MySQL アプリケーションのダウンタイムに対応する余裕はありません。

クラスターおよび関連アプリケーションのテストサイクルは、Aurora MySQL データベースエンジンの更新ごとに時間がかかります。

Aurora MySQL クラスターのデータベースバージョンには、アプリケーションに必要なすべての DB エンジン機能とバグ修正が含まれています。
```

私の推奨は、オンのままにしておくことです。データベースは、このマイナー アップデートに対してダウンタイムなしのアップグレードを試行しますが、再起動が必要な場合に備えて、ワークロードが最小のときに「メンテナンス ウィンドウ」を設定することを検討してください。

**Comment by jl4nz** [comment]
たとえば、私のデータベース イベント ログは次のようになります:

ダウンタイムなしで 24 秒かかりました。

```

July 29, 2024, 22:02 (UTC+09:00) | Attempting to upgrade the database with zero downtime.
-- | --
July 29, 2024, 22:02 (UTC+09:00) | Attempt to upgrade the database with zero downtime finished. The process took 24826 ms, 4 connections preserved, 0 connections dropped. See the database error log for details.
July 29, 2024, 22:03 (UTC+09:00) | Database cluster engine minor version upgrade complete. Previous version: 8.0.mysql_aurora.3.04.0. New version: 8.0.mysql_aurora.3.05.2


```

**Comment by ouh-kaneko** [comment]
マイナーバージョン自動アップグレードはオンにしておくべきとのこと、理解しました。
自動でのアップグレードでは、現在、3.05（デフォルト値）に更新されるそうですが、
Auroraでは3.07までバージョンが公開されています。
手動で設定・管理する場合、最新の3.07を設定すべきでしょうか？

**Comment by jl4nz** [comment]
自動設定はデフォルトのマイナーバージョンに更新され、これらのバージョンは年に数回リリースされます。

https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html#Aurora.VersionPolicy.AMVU
> デフォルトのマイナーバージョンについて実行されます。

現在、3.05.2 がデフォルトのマイナー バージョンであり、他のアップデートも利用可能ですが、アップグレードしてもセキュリティやパフォーマンスに大きな影響は及ばないはずです。

**Comment by jl4nz** [comment]
前の質問にお答えすると、必要なバージョンを選択できますが、機能上の問題がない場合は、「自動マイナー」で十分です。

**Comment by ouh-kaneko** [comment]
回答ありがとうございます。
バージョンの指定について、デフォルトで問題ないことも理解しました。
組織ポリシーを考慮し、設定を行いたいと考えます。
このissueはクローズしたいと思います、ありがとうございました。
