### ISSUE TITLE
unattended-upgradesによる更新処理について

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#59]
DockerFileにて、unattended-upgradesがインストールされていることを確認しました。
このミドルウェアは、日々、パッケージやセキュリティパッチの自動更新を行うものと認識しています。
ただ、自動更新後に再起動を行われることは、サーバー運用上、問題となりうると考えます。
こちらのミドルウェアはインストール、実行すべきでしょうか？

※aptに関して、インストール処理後にclearを実行していますので、実際には動作しないこともありうるのでしょうか？

**Comment by jl4nz** [comment]
重要なパッケージのアップグレードはイメージ プロバイダーによって行われます。同じイメージを再起動すると、実行時に行われた更新がリセットされます。

最新のイメージを確実に使用するには、新しい REDCap docker イメージ ビルドを実行します。

https://github.com/aws-samples/redcap-on-aws/blob/main/README.ja.md#3-%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89%E3%81%A8%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E3%81%AE%E5%AE%9F%E8%A1%8C


たとえば、このプロジェクトで使用されている画像は 4 日前に更新されました。

https://gallery.ecr.aws/docker/library/php

![Screenshot 2024-08-06 at 10 54 15](https://github.com/user-attachments/assets/c07f96d9-785a-4b5d-a6a8-2c131a26148f)

**Comment by ouh-kaneko** [comment]
回答ありがとうございます。
重要なパッケージのアップグレードは、REDCap dockerイメージのビルドで行う必要があることを理解しました。
そのため、Dockerfile内でunattended-upgradesがインストールされていますが、これを削除して活用したいと考えています。

**Comment by jl4nz** [comment]
Docker は現在、ルートレスの www-data ユーザーで実行されているため、自動アップグレードは機能しないと思います。

ビルドからパッケージを削除しても問題ないと思います。次のリリースのタスクにこれを追加します。

ありがとうございます!

**Comment by ouh-kaneko** [comment]
修正ありがとうございます。
mainブランチにマージされましたので、クローズとします。
