### ISSUE TITLE
外部DNSを使用する場合の設定に関する質問

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#61]
自組織のドメインを使用するため、AWS以外の外部DNSプロバイダーを使用予定です。
ただ、外部DNSプロバイダーにはNSレコードは登録出来ません。
その場合の方法としては、下記の流れで設定を行えば良いのでしょうか。

①デプロイ時は、hostInRoute53＝false、domain、subdomainは設定しない（Route53は作成しない）
②AppRunnerでカスタムドメインを手動で設定しCNAMEレコードを発行し、外部DNSプロバイダーに登録
③SESでドメインIDを手動で設定しCNAME、MX、TXTレコードを発行し、外部DNSプロバイダーに登録

**Comment by jl4nz** [comment]
はい、appRunner を 1 つ以上のドメインで手動で構成することは可能です。SES も手動で行うことができます。

新しい CNAME を生成する新しい appRunner インスタンスを必要とする変更をデプロイする場合は、CNAME の変更を追跡する際に注意してください。

現在、CDK がこれをネイティブにサポートするのを待っています。https://github.com/aws/apprunner-roadmap/issues/129 は、まだ進行中の問題です。

**Comment by ouh-kaneko** [comment]
回答ありがとうございます。
上記の方法で設定を行いたいと考えます。
