### ISSUE TITLE
docs/images/architecture.png について

### ISSUE THREAD

**Issue by ouh-hs** [aws-samples/redcap-on-aws#62]
docs/images/architecture.pngについて質問です。

①AppRunner等が配置されたサブネットが「Isolated egress subnet」となっておりますが、
　どちらかというとAuroraが配置されたサブネットが「Isolated egress subnet」かと思いました。
　実際にデプロイした環境ではAuroraが配置されたサブネットが「isolated-subnet」の名称になっています。
②VPC内からS3へのアクセスはNAT経由となっておりますが、
　実際にデプロイした環境ではS3用のエンドポイントが配置されています。
　ルートテーブルからも、S3へのアクセスはエンドポイント経由で行われているかと思うのですが、
　いかがでしょうか・・？

**Comment by jl4nz** [comment]
画像ではわかりにくいです。こちらで更新しました https://github.com/aws-samples/redcap-on-aws/blob/docs-update-108/docs/images/architecture.png

AppRunner と ECS は「Private egress only subnets」にあり、データベースは「Isolated subnets」にあります。

この問題を提起していただきありがとうございます。

**Comment by ouh-hs** [comment]
更新ありがとうございます。

②の方の質問については、誤りに気付きました。
CodeBuildからのアクセスなのでNAT経由ですね。（AppRunnerからのアクセスと勘違いしていました）

issueクローズさせていただきます。
