### ISSUE TITLE
S3バケットのCORS設定について

### ISSUE THREAD

**Issue by ouh-hs** [aws-samples/redcap-on-aws#68]
REDCapからファイルアップロードするバケットにCORSの設定がされていますが、これは意図的なものでしょうか？
CORS設定を削除して検証してみましたが、CORS設定はなくてもファイルアップロードは問題なくできました。

**Comment by jl4nz** [comment]
CORS 設定は、REDCap アプリケーションとベース URL にのみ関連しています。

現時点では、S3 バケットには CORS 制限はありません。バケット設定はここにあります:
https://github.com/aws-samples/redcap-on-aws/blob/main/prototyping/overrides/BucketProps.ts

ワークロードには S3 の CORS が必要ですか?

**Comment by ouh-hs** [comment]
ワークロードに S3 の CORSは不要と考えています。
sstのデフォルトがtrueなので、CORSの設定が自動で入っているようです。
不要な場合は「BucketProps.ts」に「cors: false,」を追加すればよいでしょうか？

https://docs.sst.dev/constructs/Bucket
> cors?
> Type : boolean | Array<[BucketCorsRule](https://docs.sst.dev/constructs/Bucket#bucketcorsrule)>
> 
Default : true

**Comment by jl4nz** [comment]
いいえ、これは「default:true」または許可されたドメインのリストである必要があります。これは AppRunner では動的であるため、少し扱いに​​くいです。

「default:true」は、任意のドメイン名からの CORS を許可します。false は、REDCap アプリを含むすべてのアクセスをブロックする可能性があります。

REDCap Web アプリ URL 経由でのみ S3 アクセスを許可する場合は、それを提供できます。この方法では、デプロイされた REDCap URL 経由でない限り、ユーザーはデータをアップロードできません。

**Comment by ouh-hs** [comment]
> false は、REDCap アプリを含むすべてのアクセスをブロックする可能性があります。
> REDCap Web アプリ URL 経由でのみ S3 アクセスを許可する場合は、それを提供できます。
> この方法では、デプロイされた REDCap URL 経由でない限り、ユーザーはデータをアップロードできません。

ありがとうございます。
他システムとの連携などをしない限り、S3へのアクセスはREDCap Web アプリ経由のみであるため、
「REDCap Web アプリ URL 経由でのみ S3 アクセスを許可」の設定にできればと思います。
AllowedOriginsにAppRunnerのデフォルトドメインを設定すれば良いでしょうか？

**Comment by jl4nz** [comment]
S3 CORS でいくつかテストしましたが、最後のコメントは間違っていました。

REDCap Web アプリケーションは S3 を直接使用しないため、CORS は使用されません。アップロードはバックエンド経由で処理されるようです。理想的には、一部の Web アプリケーションではクライアントが S3 に直接アップロードできるようにする必要があります (コストを節約) が、そうではありません。https://docs.aws.amazon.com/en_jp/AmazonS3/latest/userguide/UsingHTTPPOST.html

CORS 設定を追加するとセキュリティ体制が向上する可能性がありますが、バケットを使用する外部アプリケーションがある場合、または新しい REDCap バージョンで直接アップロードが使用されている場合のみです。

このバケットへのアクセスは、IAM ユーザー グループのユーザーにのみ許可されます。

```ts
redcapApplicationBucket.cdk.bucket.grantReadWrite(redCapS3AccessUser.userGroup);
```

**Comment by ouh-hs** [comment]
詳細なコメントありがとうございます。
現状のCDKではAllowedOriginsに「*」がセットされた状態でCORSの設定が行われたので、
セキュリティ的に何かしらの制限を設けた方が良いのでは、と思っての質問でした。

確かに「IAM ユーザー グループのユーザーにのみ許可」となっているので、問題なさそうですね。

REDCap Web アプリケーションでCORS は使用されていないのであれば、できれば少し混乱してしまうため、CORSの設定はなしの状態にしたいですが、CDK側で調整は可能でしょうか？

**Comment by jl4nz** [comment]
はい、理想的にはこれができるでしょう:

```ts
const redcapApplicationBucket = new Bucket(stack, 'appBucket', {
    cdk: {
      bucket: {
        ...bucketProps(app, redcapApplicationBucketLogs),
      },
    },
    cors: false, // new change
  });
```

いくつかのテストを実行する必要があり、これをコードに組み込むことができます

**Comment by ouh-hs** [comment]
ありがとうございます！こちらの環境でも試してみます。

**Comment by ouh-hs** [comment]
こちらの環境で試してみたところ、CORSの設定は消えましたが、REDCapでのファイルアップロード/ダウンロードは問題なくできました。また、ログ保管用のバケットにも問題なくログが出力されました。

**Comment by jl4nz** [comment]
私も同じ結果を得ています。これを更新しても問題ないはずです。明日にはリリースできると思います。

検証していただきありがとうございました。

**Comment by jl4nz** [comment]
リリース 1.0.10 で修正されました

**Comment by ouh-hs** [comment]
リリース確認いたしました。ありがとうございました!!
