### ISSUE TITLE
同一AWSアカウントに複数環境を構築した際のEC2スタックの問題

### ISSUE THREAD

**Issue by ouh-kaneko** [aws-samples/redcap-on-aws#69]
同一のAWSアカウントでstageを変更して環境を構築した際、
EC2スタック内で「deleteStackSfnLogGroup」のロググループが既に存在するため、
２つ目の環境構築時にエラーとなりました。

EC2Server.tsで、logGroupNameを指定して作成しているために起きたエラーだと考えます。

**Comment by jl4nz** [comment]
ご報告ありがとうございます。
はい、次の行を削除したほうがよいかもしれません:

`logGroupName:'/aws/vendedlogs/states/deleteStackSfnLogGroup',`

また、さまざまなデプロイメントに対して自動的に生成されるはずです。
