### ISSUE TITLE
Deployment Error: AWS::WAFv2::IPSet CREATE_FAILED due to Model Validation Failure 

### ISSUE THREAD

**Issue by tomotsuguseki** [aws-samples/redcap-on-aws#9]
Hello,

I am attempting to deploy REDCap in my AWS environment using the command `yarn deploy --stage dev`. 
Unfortunately, I encountered an error during the deployment process that I am unable to resolve on my own. I am seeking assistance to understand and fix this issue.

Error Description:
During the deployment process, the creation of the AWS WAFv2 IPSet resource failed with the following error message:

> Backend dev-REDCap-appwaf AWS::WAFv2::IPSet CREATE_FAILED Resource handler returned message: "Model validation failed (#/Addresses/0: expected minLength: 1, actual: 0)" (RequestToken: 0fc0b00b-0b5d-0938-7aa7-2b046ab6c2f6, HandlerErrorCode: InvalidRequest)

I would greatly appreciate any guidance on how to resolve this error.
Thank you in advance for your help and support.

Best regards,
Tomo

**Comment by katayohe** [comment]
Thank you for creating your first issue.

There seems to be an error related to the AWS WAFv2 IPSet.
Have you set the permitted IP ranges as follows?

>For requests that originated from the IP address 192.0.2.44, specify 192.0.2.44/32 .
>For requests that originated from IP addresses from 192.0.2.0 to 192.0.2.255, specify 192.0.2.0/24 .  

[AWS CDK Reference Documentation - class CfnIPSet (construct) ](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2.CfnIPSet.html#addresses)

You can check your current My IP Address using a site like [https://whatismyipaddress.com/](https://whatismyipaddress.com/) or [http://checkip.amazonaws.com/](http://checkip.amazonaws.com/).

and, Here is the README doc about the WAF configuration part.
https://github.com/aws-samples/redcap-on-aws/blob/a3717cd2f2c01d5de402b820688a938d7f586721/docs/ja/waf.md

Best
